# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_nodejs_app:
    name: build_nodejs_app
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - run: |
        echo "Packaging a binary executable"
        VERSION=$(git rev-parse HEAD)
        pkg src/index.js -o 'binary-'$VERSION
        echo "latest package name: binary-$VERSION"
        echo "artifactPath=$(ls binary-*)" >> $GITHUB_ENV
    - uses: actions/upload-artifact@v2
      with:
        name: artifact
        path: ${{ env.artifactPath }}

  # deploy_nodejs_app:
  #   name: deploy_nodejs_app
  #   needs: build_nodejs_app
  #   runs-on: [self-hosted, deployment]
  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: actions/setup-node@v2
  #     with:
  #       node-version: 16.x
  #       cache: 'npm'
  #   - uses: actions/download-artifact@v2
  #     with:
  #       name: artifact
  #   - run: |
  #       echo "deploying app and will expose port 8081"
  #       bin_file=$(ls binary-* | head -n 1)
  #       chmod +x $bin_file
  #       nohup ./$bin_file > app_log  2>&1 &
  #   - run: echo "application deployed and listening on port 8081"

  deploy_nodejs_app:
    name: deploy_nodejs_app
    needs: build_nodejs_app
    runs-on: [self-hosted, deployment]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      with:
        name: artifact
    - uses: vinay-nandipur/local_node_action@v1.0.0
